/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProfilePictureService } from "../profilePicture.service";
import { ProfilePictureCreateInput } from "./ProfilePictureCreateInput";
import { ProfilePicture } from "./ProfilePicture";
import { ProfilePictureFindManyArgs } from "./ProfilePictureFindManyArgs";
import { ProfilePictureWhereUniqueInput } from "./ProfilePictureWhereUniqueInput";
import { ProfilePictureUpdateInput } from "./ProfilePictureUpdateInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

export class ProfilePictureControllerBase {
  constructor(protected readonly service: ProfilePictureService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProfilePicture })
  async createProfilePicture(
    @common.Body() data: ProfilePictureCreateInput
  ): Promise<ProfilePicture> {
    return await this.service.createProfilePicture({
      data: data,
      select: {
        createdAt: true,
        id: true,
        imageUrl: true,
        updatedAt: true,
        uploadedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ProfilePicture] })
  @ApiNestedQuery(ProfilePictureFindManyArgs)
  async profilePictures(
    @common.Req() request: Request
  ): Promise<ProfilePicture[]> {
    const args = plainToClass(ProfilePictureFindManyArgs, request.query);
    return this.service.profilePictures({
      ...args,
      select: {
        createdAt: true,
        id: true,
        imageUrl: true,
        updatedAt: true,
        uploadedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProfilePicture })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async profilePicture(
    @common.Param() params: ProfilePictureWhereUniqueInput
  ): Promise<ProfilePicture | null> {
    const result = await this.service.profilePicture({
      where: params,
      select: {
        createdAt: true,
        id: true,
        imageUrl: true,
        updatedAt: true,
        uploadedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProfilePicture })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProfilePicture(
    @common.Param() params: ProfilePictureWhereUniqueInput,
    @common.Body() data: ProfilePictureUpdateInput
  ): Promise<ProfilePicture | null> {
    try {
      return await this.service.updateProfilePicture({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          imageUrl: true,
          updatedAt: true,
          uploadedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProfilePicture })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProfilePicture(
    @common.Param() params: ProfilePictureWhereUniqueInput
  ): Promise<ProfilePicture | null> {
    try {
      return await this.service.deleteProfilePicture({
        where: params,
        select: {
          createdAt: true,
          id: true,
          imageUrl: true,
          updatedAt: true,
          uploadedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/users")
  @ApiNestedQuery(UserFindManyArgs)
  async findUsers(
    @common.Req() request: Request,
    @common.Param() params: ProfilePictureWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findUsers(params.id, {
      ...query,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        following: true,
        id: true,
        lastName: true,
        mobileNumber: true,

        profilePicture: {
          select: {
            id: true,
          },
        },

        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/users")
  async connectUsers(
    @common.Param() params: ProfilePictureWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        connect: body,
      },
    };
    await this.service.updateProfilePicture({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/users")
  async updateUsers(
    @common.Param() params: ProfilePictureWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        set: body,
      },
    };
    await this.service.updateProfilePicture({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/users")
  async disconnectUsers(
    @common.Param() params: ProfilePictureWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        disconnect: body,
      },
    };
    await this.service.updateProfilePicture({
      where: params,
      data,
      select: { id: true },
    });
  }
}
