/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Otp } from "./Otp";
import { OtpCountArgs } from "./OtpCountArgs";
import { OtpFindManyArgs } from "./OtpFindManyArgs";
import { OtpFindUniqueArgs } from "./OtpFindUniqueArgs";
import { CreateOtpArgs } from "./CreateOtpArgs";
import { UpdateOtpArgs } from "./UpdateOtpArgs";
import { DeleteOtpArgs } from "./DeleteOtpArgs";
import { User } from "../../user/base/User";
import { OtpService } from "../otp.service";
@graphql.Resolver(() => Otp)
export class OtpResolverBase {
  constructor(protected readonly service: OtpService) {}

  async _otpsMeta(
    @graphql.Args() args: OtpCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Otp])
  async otps(@graphql.Args() args: OtpFindManyArgs): Promise<Otp[]> {
    return this.service.otps(args);
  }

  @graphql.Query(() => Otp, { nullable: true })
  async otp(@graphql.Args() args: OtpFindUniqueArgs): Promise<Otp | null> {
    const result = await this.service.otp(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Otp)
  async createOtp(@graphql.Args() args: CreateOtpArgs): Promise<Otp> {
    return await this.service.createOtp({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Otp)
  async updateOtp(@graphql.Args() args: UpdateOtpArgs): Promise<Otp | null> {
    try {
      return await this.service.updateOtp({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Otp)
  async deleteOtp(@graphql.Args() args: DeleteOtpArgs): Promise<Otp | null> {
    try {
      return await this.service.deleteOtp(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Otp): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
