/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OtpService } from "../otp.service";
import { OtpCreateInput } from "./OtpCreateInput";
import { Otp } from "./Otp";
import { OtpFindManyArgs } from "./OtpFindManyArgs";
import { OtpWhereUniqueInput } from "./OtpWhereUniqueInput";
import { OtpUpdateInput } from "./OtpUpdateInput";

export class OtpControllerBase {
  constructor(protected readonly service: OtpService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Otp })
  async createOtp(@common.Body() data: OtpCreateInput): Promise<Otp> {
    return await this.service.createOtp({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        expirationTime: true,
        id: true,
        otpCode: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Otp] })
  @ApiNestedQuery(OtpFindManyArgs)
  async otps(@common.Req() request: Request): Promise<Otp[]> {
    const args = plainToClass(OtpFindManyArgs, request.query);
    return this.service.otps({
      ...args,
      select: {
        createdAt: true,
        expirationTime: true,
        id: true,
        otpCode: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Otp })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async otp(@common.Param() params: OtpWhereUniqueInput): Promise<Otp | null> {
    const result = await this.service.otp({
      where: params,
      select: {
        createdAt: true,
        expirationTime: true,
        id: true,
        otpCode: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Otp })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOtp(
    @common.Param() params: OtpWhereUniqueInput,
    @common.Body() data: OtpUpdateInput
  ): Promise<Otp | null> {
    try {
      return await this.service.updateOtp({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          expirationTime: true,
          id: true,
          otpCode: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Otp })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOtp(
    @common.Param() params: OtpWhereUniqueInput
  ): Promise<Otp | null> {
    try {
      return await this.service.deleteOtp({
        where: params,
        select: {
          createdAt: true,
          expirationTime: true,
          id: true,
          otpCode: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
